/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package university.UserInterfaces.WorkAreas.Faculty;

import java.awt.CardLayout;
import javax.swing.JPanel;
import university.Business.Business;
import university.Business.UserAccounts.UserAccount;

/**
 *
 * @author jamie
 */
public class FacultyWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel CardSequencePanel;
    private Business business;
    private UserAccount userAccount;

    ManageCoursesJPanel manageCoursesJPanel = new ManageCoursesJPanel(CardSequencePanel);
    ManageProfileJPanel manageProfileJPanel = new ManageProfileJPanel(CardSequencePanel);
    StudentGradesJPanel studentGradesJPanel = new StudentGradesJPanel(CardSequencePanel);
    StudentProfilesJPanel studentProfilesJPanel = new StudentProfilesJPanel(CardSequencePanel);

    /**
     * Creates new form FacultyWorkAreaJPanel
     */
    
    public FacultyWorkAreaJPanel(Business business, UserAccount userAccount, JPanel csp) {

        this.CardSequencePanel = csp;
        this.business = business;
        this.userAccount = userAccount;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFacultyMember = new javax.swing.JLabel();
        btnManageCourses = new javax.swing.JButton();
        btnManageProfile = new javax.swing.JButton();
        btnStudentGrades = new javax.swing.JButton();
        btnStudentProfile = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        lblFacultyMember.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblFacultyMember.setText("Faculty Member Dashboard");

        btnManageCourses.setText("Manage Courses");
        btnManageCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCoursesActionPerformed(evt);
            }
        });

        btnManageProfile.setText("Manage Profile");
        btnManageProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProfileActionPerformed(evt);
            }
        });

        btnStudentGrades.setText("Student Grades");
        btnStudentGrades.setSize(new java.awt.Dimension(150, 40));
        btnStudentGrades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentGradesActionPerformed(evt);
            }
        });

        btnStudentProfile.setText("Student Profiles");
        btnStudentProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(lblFacultyMember))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnStudentGrades, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnStudentProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManageProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManageCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblFacultyMember)
                .addGap(48, 48, 48)
                .addComponent(btnManageCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnManageProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnStudentGrades, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnStudentProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCoursesActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.add("manageCoursesJPanel", manageCoursesJPanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnManageCoursesActionPerformed

    private void btnManageProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProfileActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.add("manageProfileJPanel", manageProfileJPanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnManageProfileActionPerformed

    private void btnStudentGradesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentGradesActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.add("studentGradesJPanel", studentGradesJPanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnStudentGradesActionPerformed

    private void btnStudentProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentProfileActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.add("studentProfilesJPanel", studentProfilesJPanel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnStudentProfileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageCourses;
    private javax.swing.JButton btnManageProfile;
    private javax.swing.JButton btnStudentGrades;
    private javax.swing.JButton btnStudentProfile;
    private javax.swing.JLabel lblFacultyMember;
    // End of variables declaration//GEN-END:variables
}
