package university.UserInterfaces.WorkAreas.AdminRole;

import university.Business.Business;
import university.Business.UserAccounts.UserAccount;
import university.Business.UserAccounts.UserAccountDirectory;
import university.UserInterfaces.WorkAreas.AdminRole.AdminiterUserAccountWork.AddAccountJPanel;
import university.UserInterfaces.WorkAreas.AdminRole.AdminiterUserAccountWork.AdminUserAccount;
import university.UserInterfaces.WorkAreas.AdminRole.AdminiterUserAccountWork.ManageUserAccountsJPanel;

import javax.swing.JPanel;

/**
 *
 * @author sange
 */
public class AdminRoleWorkAreaJPanel extends javax.swing.JPanel {

    javax.swing.JPanel CardSequencePanel;
    Business business;
    UserAccount selectedAccount;

    String MANAGE_STUDENT = "ManagaeStudent";
    String MANAGE_FACULTY = "ManagaeFaculty";
    String MANAGE_ALL_ACCOUNTS = "ManageAllUsers";

    /**
     * Creates new form UnitRiskWorkArea
     */
    public AdminRoleWorkAreaJPanel(Business b, UserAccount useraccount, JPanel clp) {

        this.business = b;
        this.CardSequencePanel = clp;
        this.selectedAccount = useraccount;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdministerUserAccounts = new javax.swing.JButton();
        btnManageFaculty = new javax.swing.JButton();
        btnRegisterPerson = new javax.swing.JButton();
        btnManageProfile = new javax.swing.JButton();
        btnManageStudents = new javax.swing.JButton();

        setBackground(new java.awt.Color(176, 224, 230));
        setForeground(new java.awt.Color(51, 51, 51));

        btnAdministerUserAccounts.setFont(getFont());
        btnAdministerUserAccounts.setForeground(new java.awt.Color(102, 102, 102));
        btnAdministerUserAccounts.setText("Administer User Accounts");
        btnAdministerUserAccounts.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdministerUserAccounts.setMaximumSize(new java.awt.Dimension(200, 40));
        btnAdministerUserAccounts.setMinimumSize(new java.awt.Dimension(20, 23));
        btnAdministerUserAccounts.setPreferredSize(new java.awt.Dimension(240, 30));
        btnAdministerUserAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministerUserAccountsIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        btnManageFaculty.setFont(getFont());
        btnManageFaculty.setForeground(new java.awt.Color(102, 102, 102));
        btnManageFaculty.setText("Manage Faculty");
        btnManageFaculty.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageFaculty.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageFaculty.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManageFaculty.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManageFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageFacultyActionPerformed(evt);
            }
        });

        btnRegisterPerson.setFont(getFont());
        btnRegisterPerson.setForeground(new java.awt.Color(102, 102, 102));
        btnRegisterPerson.setText("Register  Persons (HR)");
        btnRegisterPerson.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegisterPerson.setMaximumSize(new java.awt.Dimension(200, 40));
        btnRegisterPerson.setMinimumSize(new java.awt.Dimension(20, 20));
        btnRegisterPerson.setPreferredSize(new java.awt.Dimension(240, 25));
        btnRegisterPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterPersonActionPerformed(evt);
            }
        });

        btnManageProfile.setFont(getFont());
        btnManageProfile.setForeground(new java.awt.Color(102, 102, 102));
        btnManageProfile.setText("My Profile");
        btnManageProfile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageProfile.setMaximumSize(new java.awt.Dimension(145, 40));
        btnManageProfile.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManageProfile.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManageProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProfileIdentifyEventsActionPerformed(evt);
            }
        });

        btnManageStudents.setFont(getFont());
        btnManageStudents.setForeground(new java.awt.Color(102, 102, 102));
        btnManageStudents.setText("Manage Students");
        btnManageStudents.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageStudents.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageStudents.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManageStudents.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManageStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStudentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManageProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnManageFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdministerUserAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegisterPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManageStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(632, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegisterPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdministerUserAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(btnManageProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdministerUserAccountsIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministerUserAccountsIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:

        ManageUserAccountsJPanel aos = new ManageUserAccountsJPanel(business, CardSequencePanel, MANAGE_ALL_ACCOUNTS);

        CardSequencePanel.add("ManageVulns", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_btnAdministerUserAccountsIdentifyResourceAssetsActionPerformed

    private void btnRegisterPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterPersonActionPerformed
        // TODO add your handling code here:

        AddAccountJPanel aos = new AddAccountJPanel(business, CardSequencePanel, MANAGE_ALL_ACCOUNTS);

        CardSequencePanel.add("AddAccountJPanel", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_btnRegisterPersonActionPerformed

    private void btnManageStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStudentsActionPerformed
        // TODO add your handling code here:
        ManageUserAccountsJPanel aos = new ManageUserAccountsJPanel(business, CardSequencePanel, MANAGE_STUDENT);

        CardSequencePanel.add("ManageVulns", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnManageStudentsActionPerformed

    private void btnManageProfileIdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProfileIdentifyEventsActionPerformed

        MyProfile myProfile = new MyProfile(business, selectedAccount, CardSequencePanel);

        CardSequencePanel.add("MyProfile", myProfile);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnManageProfileIdentifyEventsActionPerformed

    private void btnManageFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageFacultyActionPerformed
        ManageUserAccountsJPanel aos = new ManageUserAccountsJPanel(business, CardSequencePanel, MANAGE_FACULTY);

        CardSequencePanel.add("ManageVulns", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnManageFacultyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministerUserAccounts;
    private javax.swing.JButton btnManageFaculty;
    private javax.swing.JButton btnManageProfile;
    private javax.swing.JButton btnManageStudents;
    private javax.swing.JButton btnRegisterPerson;
    // End of variables declaration//GEN-END:variables

}
