package university.UserInterfaces.WorkAreas.AdminRole;

import university.Business.Business;
import university.Person.Student.StudentProfile;
import university.Business.UserAccounts.UserAccount;
import university.Business.UserAccounts.UserAccountDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * h
 *
 * @author sange
 */
public class MyProfile extends javax.swing.JPanel {

    JPanel CardSequencePanel;
    Business business;
    UserAccount selecteduseraccount;

    public MyProfile(Business business, UserAccount sua, JPanel jp) {

        this.business = business;
        this.CardSequencePanel = jp;
        this.selecteduseraccount = sua;
        initComponents();

        refreshTextField();
        setViewMode();
        hideFields();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblEmailAddress = new javax.swing.JLabel();
        lblAccountStatus = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblNuId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtEmailAddress = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        txtNuId = new javax.swing.JTextField();
        comboAccountStatus = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(176, 224, 230));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("My Profile");
        add(jLabel2);
        jLabel2.setBounds(130, 50, 310, 28);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(10, 10, 100, 23);

        lblId.setText("ID: ");
        add(lblId);
        lblId.setBounds(130, 110, 90, 16);

        lblLastName.setText("Last Name:");
        add(lblLastName);
        lblLastName.setBounds(130, 200, 90, 16);

        lblEmailAddress.setText("Email Address: ");
        add(lblEmailAddress);
        lblEmailAddress.setBounds(130, 280, 90, 16);

        lblAccountStatus.setText("Account Status:");
        add(lblAccountStatus);
        lblAccountStatus.setBounds(130, 360, 90, 16);

        lblPhoneNumber.setText("Phone Number:");
        add(lblPhoneNumber);
        lblPhoneNumber.setBounds(130, 320, 90, 16);

        lblFirstName.setText("First Name:");
        add(lblFirstName);
        lblFirstName.setBounds(130, 150, 90, 16);

        lblNuId.setText("NUID:");
        add(lblNuId);
        lblNuId.setBounds(130, 240, 90, 16);

        txtId.setEnabled(false);
        add(txtId);
        txtId.setBounds(270, 110, 200, 30);

        txtId.setEnabled(false);
        add(txtFirstName);
        txtFirstName.setBounds(270, 150, 200, 30);

        txtId.setEnabled(false);
        add(txtLastName);
        txtLastName.setBounds(270, 190, 200, 30);

        txtId.setEnabled(false);
        add(txtEmailAddress);
        txtEmailAddress.setBounds(270, 270, 200, 30);

        txtId.setEnabled(false);
        add(txtPhoneNumber);
        txtPhoneNumber.setBounds(270, 310, 200, 30);

        txtId.setEnabled(false);
        add(txtNuId);
        txtNuId.setBounds(270, 230, 200, 30);

        comboAccountStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));
        comboAccountStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAccountStatusActionPerformed(evt);
            }
        });
        add(comboAccountStatus);
        comboAccountStatus.setBounds(270, 350, 200, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);


    }//GEN-LAST:event_btnBackActionPerformed

    private void comboAccountStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAccountStatusActionPerformed

    }//GEN-LAST:event_comboAccountStatusActionPerformed

    private void refreshTextField() {

        txtId.setText(selecteduseraccount.getProfile().getPerson().getId());
        txtFirstName.setText(selecteduseraccount.getProfile().getPerson().getFirstName());
        txtLastName.setText(selecteduseraccount.getProfile().getPerson().getLastName());
        txtPhoneNumber.setText(String.valueOf(selecteduseraccount.getProfile().getPerson().getPhoneNumber()));
        txtEmailAddress.setText(selecteduseraccount.getProfile().getPerson().getEmailId());
        comboAccountStatus.setSelectedItem(selecteduseraccount.getAccountStatus());
        if (selecteduseraccount.getProfile() instanceof StudentProfile) {
            txtNuId.setText(((StudentProfile) selecteduseraccount.getProfile()).getNuId());
        }

    }

    private void setViewMode() {

        txtId.setEnabled(false);
        txtFirstName.setEnabled(false);
        txtLastName.setEnabled(false);
        txtPhoneNumber.setEnabled(false);
        txtEmailAddress.setEnabled(false);
        comboAccountStatus.setEnabled(false);
        txtNuId.setEnabled(false);
    }

    private void hideFields() {
        if (selecteduseraccount.getProfile() instanceof StudentProfile) {
            comboAccountStatus.setVisible(false);
            lblAccountStatus.setVisible(false);
            lblId.setVisible(false);
            lblPhoneNumber.setVisible(false);
            txtPhoneNumber.setVisible(false);
            lblEmailAddress.setVisible(false);
            txtEmailAddress.setVisible(false);
            txtId.setVisible(false);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> comboAccountStatus;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAccountStatus;
    private javax.swing.JLabel lblEmailAddress;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblNuId;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtNuId;
    private javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables

}
