/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package university.UserInterfaces.WorkAreas.Student;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import university.Business.Business;
import university.Business.UserAccounts.UserAccount;

/**
 *
 * @author Jafaeth Gomez
 */
public class CourseworkPanel extends javax.swing.JPanel {
    Business business;
    UserAccount userAccount;
    javax.swing.JPanel CardSequencePanel;
  

  
    /**
     * Creates new form CourseworkPanel
     */
    public CourseworkPanel(Business business, UserAccount userAccount, javax.swing.JPanel cardPanel) {
    initComponents();
    this.business = business;
    this.userAccount = userAccount;
    this.CardSequencePanel = cardPanel;
    seedAssignments(); // call this once at startup
}

private void seedAssignments() {
    javax.swing.table.DefaultTableModel dtm =
    (javax.swing.table.DefaultTableModel) jTable1.getModel();
    dtm.setRowCount(0);
    dtm.setColumnIdentifiers(new Object[]{"Course", "Assignment", "Status", "Submitted On"});

    dtm.addRow(new Object[]{"BIO101", "Lab 1", "Not Submitted", "-"});
    dtm.addRow(new Object[]{"CHEM210", "Project Proposal", "Not Submitted", "-"});
    dtm.addRow(new Object[]{"MATH221", "HW 2", "Submitted", "2025-10-20"});

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblcoursework = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblcoursework.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblcoursework.setText("Manage Coursework");
        add(lblcoursework, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 240, -1));

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 236, 95, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 236, 95, -1));

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 100, -1));

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 90, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 460, 170));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
       if (CardSequencePanel != null) {
        ((java.awt.CardLayout) CardSequencePanel.getLayout())
            .first(CardSequencePanel);
    }
    
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Please select a coursework row to save.");
        return;
    }

    javax.swing.table.DefaultTableModel dtm =
        (javax.swing.table.DefaultTableModel) jTable1.getModel();
    String course = (String) dtm.getValueAt(row, 0);
    String assignment = (String) dtm.getValueAt(row, 1);
    JOptionPane.showMessageDialog(this, "Coursework saved:\nCourse: " + course + "\nAssignment: " + assignment);

        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
         int r = jTable1.getSelectedRow();
    if (r < 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Select an assignment to submit.");
        return;
    }
    javax.swing.table.DefaultTableModel dtm =
        (javax.swing.table.DefaultTableModel) jTable1.getModel();
    dtm.setValueAt("Submitted", r, 2);
    dtm.setValueAt(java.time.LocalDate.now().toString(), r, 3);
    javax.swing.JOptionPane.showMessageDialog(this, "Assignment submitted.");

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        seedAssignments();

    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblcoursework;
    // End of variables declaration//GEN-END:variables

}
