/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package university.UserInterfaces.WorkAreas.Student;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import university.Business.Business;
import university.Business.UserAccounts.UserAccount;
/**
 *
 * @author Jafaeth Gomez
 */

public class RegisterCoursesPanel extends javax.swing.JPanel {


    private final Business business;
    private final UserAccount userAccount;
    private final JPanel cardContainer;
    private static final int COL_ID = 0;
    private static final int COL_TITLE = 1;
    private static final int COL_CREDITS = 2;
    private static final int COL_STATUS = 3;

 
    public RegisterCoursesPanel() {
        this.business = null;
        this.userAccount = null;
        this.cardContainer = null;
        initComponents();
        configureTable();
        loadCourses();
    }

    /** Preferred constructor called from StudentWorkAreaJPanel */
    public RegisterCoursesPanel(Business b, UserAccount ua, JPanel container) {
        this.business = b;
        this.userAccount = ua;
        this.cardContainer = container;
        
       
        initComponents();
        configureTable();
        loadCourses();
    }

    private void configureTable() {
        DefaultTableModel model = new DefaultTableModel(
        new Object[][]{},
        new String[] { "Course ID", "Title", "Credits", "Status" }
    ) {
        @Override public boolean isCellEditable(int row, int col) { return false; }
    };
    tblCourses.setModel(model);
    tblCourses.setRowHeight(22);
    tblCourses.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
}
    private void loadCourses() {
       DefaultTableModel model = (DefaultTableModel) tblCourses.getModel();
    model.setRowCount(0);
    model.addRow(new Object[]{"INFO 5100", "App Engineering & Dev", 4, "Available"});
    model.addRow(new Object[]{"INFO 6150", "Web Design & UX",      4, "Available"});
    model.addRow(new Object[]{"CSYE 6200", "Object-Oriented Design",4, "Available"});

    }
    
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourses = new javax.swing.JTable();
        btnEnroll = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnDrop = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        lblTitle.setBackground(new java.awt.Color(204, 204, 204));
        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("Course Registration ");

        tblCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCourses);

        btnEnroll.setText("Enroll Selected");
        btnEnroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnDrop.setText("Drop Selected");
        btnDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDropActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEnroll, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(btnDrop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(btnEnroll, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRefresh)
                    .addComponent(btnDrop, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
      if (cardContainer != null && cardContainer.getLayout() instanceof CardLayout) {
        ((CardLayout) cardContainer.getLayout()).first(cardContainer);  // go home
    } else {
        javax.swing.JOptionPane.showMessageDialog(
            this, "Navigation container not set.", "Navigation", javax.swing.JOptionPane.WARNING_MESSAGE
        );
    }
                
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadCourses();

    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnEnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollActionPerformed
        // TODO add your handling code here:
           int row = tblCourses.getSelectedRow();
    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Please select a course to enroll.");
        return;
    }

    DefaultTableModel dtm = (DefaultTableModel) tblCourses.getModel();
    String current = String.valueOf(dtm.getValueAt(row, COL_STATUS));

    if ("Enrolled".equalsIgnoreCase(current)) {
        JOptionPane.showMessageDialog(this, "You're already enrolled in this course.");
        return;
    }

    dtm.setValueAt("Enrolled", row, COL_STATUS);
    String id = String.valueOf(dtm.getValueAt(row, COL_ID));
    JOptionPane.showMessageDialog(this, "Enrolled in " + id + ".");


    }//GEN-LAST:event_btnEnrollActionPerformed

    private void btnDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDropActionPerformed
        // TODO add your handling code here:
         int row = tblCourses.getSelectedRow();
    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Select a course to drop.");
        return;
    }

    DefaultTableModel dtm = (DefaultTableModel) tblCourses.getModel();
    String status = String.valueOf(dtm.getValueAt(row, COL_STATUS));

    if (!"Enrolled".equalsIgnoreCase(status)) {
        JOptionPane.showMessageDialog(this, "You can only drop courses you are enrolled in.");
        return;
    }

    dtm.setValueAt("Available", row, COL_STATUS);
    String id = String.valueOf(dtm.getValueAt(row, COL_ID));
    JOptionPane.showMessageDialog(this, "Dropped " + id + ".");

      
    }//GEN-LAST:event_btnDropActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDrop;
    private javax.swing.JButton btnEnroll;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblCourses;
    // End of variables declaration//GEN-END:variables

   

  
}
