/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package university.UserInterfaces.WorkAreas.Student;

/**
 *
 * @author Jafaeth Gomez
 */
public class StudentWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentWorkAreaJPanel
     */
    public StudentWorkAreaJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblregistercourses = new javax.swing.JButton();
        lblviewtranscript = new javax.swing.JButton();
        lblviewprofile = new javax.swing.JButton();
        lbllogout = new javax.swing.JButton();
        lblstudentdashboard = new javax.swing.JLabel();

        lblregistercourses.setText("Register for Courses");

        lblviewtranscript.setText("View Transcript");

        lblviewprofile.setText("View Profile");

        lbllogout.setText("Logout");

        lblstudentdashboard.setText("Student Dashboard ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblregistercourses)
                .addGap(18, 18, 18)
                .addComponent(lblviewtranscript)
                .addGap(18, 18, 18)
                .addComponent(lblviewprofile)
                .addGap(28, 28, 28)
                .addComponent(lbllogout)
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblstudentdashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblstudentdashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblregistercourses)
                    .addComponent(lblviewtranscript)
                    .addComponent(lblviewprofile)
                    .addComponent(lbllogout))
                .addGap(97, 97, 97))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton lbllogout;
    private javax.swing.JButton lblregistercourses;
    private javax.swing.JLabel lblstudentdashboard;
    private javax.swing.JButton lblviewprofile;
    private javax.swing.JButton lblviewtranscript;
    // End of variables declaration//GEN-END:variables
}
