/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package university.UserInterfaces.WorkAreas.Student;
import university.UserInterfaces.WorkAreas.Student.AuditPanel;
import javax.swing.*;
import university.Business.Business;
import university.Business.UserAccounts.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;

/**
 *
 * @author Jafaeth Gomez
 */

    /**
     * Creates new form StudentWorkAreaJPanel
     */
    public class StudentWorkAreaJPanel extends javax.swing.JPanel {

    JPanel CardSequencePanel;
    Business business;
    UserAccount userAccount;

    public StudentWorkAreaJPanel() {
        initComponents();
    }
    public StudentWorkAreaJPanel(Business b, UserAccount ua, JPanel clp) {
        this.business = b;
        this.userAccount = ua;
        this.CardSequencePanel = clp;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegister = new javax.swing.JButton();
        btnTranscript = new javax.swing.JButton();
        btnCoursework = new javax.swing.JButton();
        btnAudit = new javax.swing.JButton();
        lblstudentdashboard = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegister.setText("Register for Courses");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 190, -1, -1));

        btnTranscript.setText("View Transcript");
        btnTranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranscriptActionPerformed(evt);
            }
        });
        add(btnTranscript, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 190, -1, -1));

        btnCoursework.setText("Manage Coursework");
        btnCoursework.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCourseworkActionPerformed(evt);
            }
        });
        add(btnCoursework, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 190, -1, -1));

        btnAudit.setText("Graduation Audit");
        btnAudit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuditActionPerformed(evt);
            }
        });
        add(btnAudit, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 190, -1, -1));

        lblstudentdashboard.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblstudentdashboard.setText("Student Dashboard ");
        add(lblstudentdashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 46, 257, 40));

        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 231, 137, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCourseworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCourseworkActionPerformed
        // TODO add your handling code here:
       CourseworkPanel cp = new CourseworkPanel(business, userAccount, CardSequencePanel);
    CardSequencePanel.add("CourseworkPanel", cp);
    ((CardLayout) CardSequencePanel.getLayout()).show(CardSequencePanel, "CourseworkPanel");


    }//GEN-LAST:event_btnCourseworkActionPerformed

    private void btnTranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranscriptActionPerformed
        // TODO add your handling code here:
        TranscriptPanel tp = new TranscriptPanel(business, userAccount, CardSequencePanel);
         CardSequencePanel.add("TranscriptPanel", tp);
        ((CardLayout) CardSequencePanel.getLayout()).show(CardSequencePanel, "TranscriptPanel");
    }//GEN-LAST:event_btnTranscriptActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
    RegisterCoursesPanel regPanel = new RegisterCoursesPanel(business, userAccount, CardSequencePanel);
    CardSequencePanel.add("RegisterPanel", regPanel);
     java.awt.CardLayout layout = (java.awt.CardLayout) CardSequencePanel.getLayout();
    layout.next(CardSequencePanel);

        
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnAuditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuditActionPerformed
        // TODO add your handling code here:
        AuditPanel ap = new AuditPanel(business, userAccount, CardSequencePanel);
    CardSequencePanel.add("AuditPanel", ap);
    ((CardLayout) CardSequencePanel.getLayout()).show(CardSequencePanel, "AuditPanel");
    }//GEN-LAST:event_btnAuditActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAudit;
    private javax.swing.JButton btnCoursework;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnTranscript;
    private javax.swing.JLabel lblstudentdashboard;
    // End of variables declaration//GEN-END:variables
    
   
}
