/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package university.UserInterfaces.WorkAreas.Student;

import university.Business.Business;
import university.Business.UserAccounts.UserAccount;

/**
 *
 * @author Jafaeth Gomez
 */
public class TranscriptPanel extends javax.swing.JPanel {

    /**
     * Creates new form TranscriptPanel
     */
    public TranscriptPanel(Business business, UserAccount userAccount, javax.swing.JPanel cardPanel) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Student Transcript");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 220, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
